### ISSUE TITLE
Enhancement: Add Connected Applications support for Mule Deploy Library

### ISSUE THREAD

**Issue by TimGonz-AVIO** [avioconsulting/mule-deploy-library#41]
We should add an option to authenticate using a connected application rather than a username and password. The list of required permissions is not currently known. Please see here for documentation regarding connected applications: [https://docs.mulesoft.com/access-management/connected-apps-developers](https://docs.mulesoft.com/access-management/connected-apps-developers)

**Comment by manikmagar** [comment]
This feature is added in PR https://github.com/avioconsulting/mule-deploy-library/pull/39.
